name: Release
on:
  push:
    tags: [ 'v*.*.*' ]
jobs:
  release-fedora:
    name: Release on Fedora Latest (Container)
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Install Deps
        run: dnf install -y cmake ninja-build openscap-utils python3-pip python3-devel gcc-c++ ansible ansible-lint libxslt
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
      - name: Install python deps
        run: pip install -r requirements-base.txt -r test-requirements.txt
      - name: Configure
        run: cmake ..
        working-directory: ./build
      - name: Build Ubuntu 24.04 only
        run: make -j2 ubuntu2404
        working-directory: ./build
      - name: Build RHEL 9 only
        run: make -j2 rhel9
        working-directory: ./build
      - name: Set Version
        id: set_version
        run: |-
          echo "tag=${GITHUB_REF/refs\/tags\//}"  >> $GITHUB_OUTPUT
          echo "ver=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT
        env:
          GITHUB_REF: ${{ github.ref }}
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@a34a8009a9588bb86b02a873cf592440e96a5da8 # v4
        with:
          configuration: .github/workflows/release-changelog.json
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          draft: True
          name: Content ${{ steps.set_version.outputs.ver }}
          tag_name: ${{ steps.set_version.outputs.tag }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          files: |
            build/ssg-ubuntu2404-ds.xml
            build/ssg-rhel9-ds.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
